name: OvTeleportAddon
version: '${project.version}'
author: OverwriteMC
main: ru.overwrite.teleports.OvTeleportAddon
api-version: 1.16
depend: [Essentials, EssentialsSpawn]
softdepend: [Vault, PlaceholderAPI]
commands:
  canceltp:
    aliases: [canceltpa, cancelteleport]
  ovteleportaddon:
    aliases: [teleportaddon]
