name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[SKIP-CI]')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-java-version: [ 16, 17, 21 ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.build-java-version }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ matrix.build-java-version }}-

      - name: Update Maven Java Version to ${{ matrix.build-java-version }}
        run: |
          sed -i "s|<java.version>.*</java.version>|<java.version>${{ matrix.build-java-version }}</java.version>|" pom.xml

      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

      - name: Upload artifact for Java ${{ matrix.build-java-version }}
        uses: actions/upload-artifact@v4
        with:
          name: OvTeleportAddon-java${{ matrix.build-java-version }}
          path: target/OvTeleportAddon-*.jar